### ISSUE TITLE
Confused about inset_theme()

### ISSUE THREAD

**Issue by XanderDes** [hughjonesd/ggmagnify#27]
Thank you very much for this nice and, generally, easy-to-use package! For a beginner like myself, a life saver.
However, I seem to be confused about the way to adjust margins on the inset, when using inset axes. I couldn't find an answer to my problem in the - excellent - Readme and thought to have found the solution in the help file of the `inset_theme()` function, esp. `margin = if (axes == "") 0 else 8`. Still, I do not get it to work.

**Describe the bug**
I do not manage to set the margin of the inset to 0 when using axes on the inset plot. Instead the margins of the main plot are adjusted.

**To Reproduce**
```
ggp <- ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Species)) + geom_point()
ggp


# Attempt 1: inset_theme() + plot()
axes <- "bla"  # without this line - Error: object 'axes' not found
Inset = ggp + inset_theme(
  blank = inset_blanks(axes = axes),
  axes,
  margin = if (axes == "") 50 else 0  # swapping '0' and '50' around shows changes in 'Inset'
)
Inset

ggm <- ggp + 
  geom_magnify(
    from = c(3, 3.5, 4.5, 5),
    to = c(3.5, 4.25, 6, 7),
    axes = "xy",
    plot = Inset)
ggm  # main plot and inset margins are not affected by if statement in inset_theme()


# Attempt 2: inset_theme() alone
ggm <- ggp + 
  geom_magnify(
    from = c(3, 3.5, 4.5, 5),
    to = c(3.5, 4.25, 6, 7),
    axes = "xy") +
  inset_theme(
    blank = inset_blanks(axes = axes),
    axes,
    margin = if (axes == "") 50 else 0
  )
ggm  # only main plot's margins are adjusted, inset plot margins remain unchanged


# Attempt 3: as Attempt 1, but just theme()
Inset = ggp + theme(
  plot.margin = unit(c(0, 0, 0, 0), "mm")) # changing the values from '0' changes the margins as expected
Inset

ggm <- ggp + 
  geom_magnify(
    from = c(3, 3.5, 4.5, 5),
    to = c(3.5, 4.25, 6, 7), axes = "xy", plot = Inset)
ggm # neither the main plot's nor the inset's margins are adjusted


# Attempt 4: as Attempt 2,  but just theme()
ggm <- ggp + 
  geom_magnify(
    from = c(3, 3.5, 4.5, 5),
    to = c(3.5, 4.25, 6, 7), axes = "xy") +
  theme(
    plot.margin = unit(c(20, 20, 20, 20), "mm"))
ggm # only the main plot's margins are adjusted

```

**Expected behavior**
I expected the `theme()` function applied to the inset and 'transferred' to the main plot via the `plot` argument in `geom_magnify()` to change the looks of the inset. This works for the background, for example. Using this logic, I assumed that the `if` statement inside the `inset_themes()` function would set the margins of the inset. However, it only affects the margins of the main plot; it doesn't matter whether `inset_themes()` is directly 'applied' to the main plot or 'transferred' via the `plot` argument in `geom_magnify()`.

**Other information**
Versions
ggmagnify: 0.4.0
`packageVersion("ggplot2")`: 3.5.1
 R: 4.3.3
Graphics device: AGG Backend

**Comment by hughjonesd** [comment]
I think you are confused about R help files. The section you see in `?inset_theme`:

# Usage
```r
inset_theme(
  blank = inset_blanks(axes = axes),
  axes,
  margin = if (axes == "") 0 else 8
)
```

represents the default arguments of the function. It is not meant to be an example to copy.  (For that, see the **Example** section - which I appreciate `inset_theme` doesn't have, and I'll fix that.)

So, in your first example, you are effectively writing

```r
Inset = ggp + inset_theme(
  blank = inset_blanks(axes = "blah"),
  "blah",
  margin = if ("blah" == "") 50 else 0  # swapping '0' and '50' around shows changes in 'Inset'
)
```

This is going to mess things up because `"blah"` isn't a valid value for `axes`, either in `inset_blanks` or `inset_theme`. For valid values, see the **Arguments** part of the help file:

```
    axes     String. Which axes to plot in the inset? "", "x", "y" or "xy".
```

Given that, you are invoking "undefined behaviour".... 

However, you are right that there is a bug here. The code in the internal function `create_plot_gtable()` always invokes `inset_theme()` itself. So, if you pass in a `plot` argument to `geom_magnify`, having edited it using `inset_theme()`, it's just gonna get overridden. In effect, this prevents the user using `inset_theme()` to customize the plot object himself, which is the purpose of making the function public. In particular, there's no way to set the margins of the inset plot because they'll always be overridden.

**Comment by hughjonesd** [comment]
Please check if it's fixed in master:

```r
library(ggplot2)
 ggp <- ggplot(iris, aes(Sepal.Width, Sepal.Length, colour = Species)) +
          geom_point() + xlim(c(2, 6))
inset <- ggp + inset_theme(
  axes = "",
  margin = 4   # or whatever number you prefer
)

ggp + 
  geom_magnify(
    from = c(3, 3.5, 4.5, 5),
    to = c(3.5, 4.25, 6, 7),
    plot = inset)
```

**Comment by XanderDes** [comment]
Hey David,

Thanks a lot for the quick follow-up! And yes, the problem is resolved in the master: inset plot margins are changing when setting the `margin `argument in `inset_theme()`, while the main plot margins stay unaffected. Great!

Just for the record, I set `axes = "blah"` as an example, thinking it would be overwritten in the later assignment `axes = "xy"` in `geom_magnify()`. Still, I did struggle to understand how to use `inset_theme()`, so an updated example section would indeed be great. In short, the combination of my noobness and the fact that the inset margins did get overridden led to my confusion.

As said though: all is well now - thanks again!
